global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api_service'
    static_configs:
      - targets: ['api_service:8000']

  - job_name: 'db_service'
    static_configs:
      - targets: ['db_service:8001']
